Feature/register products
study-spring/spring-market pull request #7
Opened 2021-09-22 08:08 UTC by mankicho

2021-09-25 07:12 UTC, Leewongi0731 commented
범근이는 개발 안함??

2021-09-25 07:27 UTC, Leewongi0731 requested changes

2021-09-25 07:27 UTC, Leewongi0731 commented on src/main/java/project/springmarket/controller/ProductController.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
@ControllerAdvice 걸어서 공통 ExceptionHandler하는 class로 분리해서 처리하는게 좋을 듯

2021-09-25 07:27 UTC, Leewongi0731 commented on src/main/java/project/springmarket/controller/ProductController.java
> +    @PostMapping("/address/")
맨 뒤 /는  빼는게 관행임

2021-09-25 07:27 UTC, Leewongi0731 commented on src/main/java/project/springmarket/model/product/ProductStatus.java
> +    판매, 예약, 판매완료;
한글보다 영문으로 바꾸는게 좋을 듯..

2021-09-25 07:27 UTC, Leewongi0731 commented on src/main/java/project/springmarket/repository/ProductRepository.java
> +    public FindProductResponseDTO findProducts(int addressNo) {
Response는 사용자의 요청에 따른 응답 객체이기 때문에, Repository level에서 만들거나 핸들링하는 것보다, 사용자의 요청을 처리하는 controller level에서 처리하는게 좋아보임. 
 Controller layer : 사용자의 요청/응답 처리 (Request model, Response model)
 Service layer : 비즈니스 로직 처리, 트랜젝션 처리
 Repository layer : DB query 호출

2021-09-25 07:27 UTC, Leewongi0731 commented on src/main/java/project/springmarket/service/ProductService.java
> +    public FindProductResponseDTO findProducts(int addressNo) {
여기도, Service에서 ResponseDTO 내리지말고, 일반 VO, DTO을 내리고 Controller에서 return할 때 ResponseDTO로 반환하는게 좋아보임

2021-09-25 07:27 UTC, Leewongi0731 commented on src/main/resources/mybatis/mapper/product.xml
> +        select *
*로 하지말고 가져올 컬럼들 명시 다 하셈
나중에 model 변경되거나 할 때 헷갈림

2021-09-25 08:26 UTC, Leewongi0731 requested changes

2021-09-25 08:26 UTC, Leewongi0731 commented on src/main/java/project/springmarket/model/product/request/FindProductDTO.java
> +public class FindProductDTO {
product/request/ 에 넣고 쓸거면, FindProductRequestDTO로 변경하는게 좋아보임.

2021-09-25 10:22 UTC, mankicho commented on src/main/java/project/springmarket/controller/ProductController.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
옥희

2021-09-25 10:22 UTC, mankicho commented on src/main/java/project/springmarket/controller/ProductController.java
> +    @PostMapping("/address/")
넹

2021-09-25 10:22 UTC, mankicho commented on src/main/java/project/springmarket/model/product/ProductStatus.java
> +    판매, 예약, 판매완료;
넵

2021-09-25 10:22 UTC, mankicho commented on src/main/java/project/springmarket/repository/ProductRepository.java
> +    public FindProductResponseDTO findProducts(int addressNo) {
오호라 좋은꿀팁 ㅅ

2021-09-25 10:22 UTC, mankicho commented on src/main/resources/mybatis/mapper/product.xml
> +        select *
냅

2021-09-29 11:55 UTC, Leewongi0731 commented on src/main/java/project/springmarket/controller/ProductController.java
> +        return FindProductResponseDTO
builder 보다 FindProductResponseDTO에 ProductVO을 인수로 받는 생성자를 만드는게 좋을 듯, 생성자 메소드 이름은 fromProductVO으로 하면 될 듯.

2021-09-29 11:55 UTC, Leewongi0731 commented on src/main/java/project/springmarket/service/ProductService.java
> +    public ProductService(ProductRepository productRepository) {
왜 이렇게 바꾼거야??  RequiredArgsConstructor로 주입해줬었잖아.

2021-09-29 13:50 UTC, Leewongi0731 commented on src/main/java/project/springmarket/controller/ProductController.java
> +    public boolean registerProduct(@RequestBody @Valid ProductRegisterRequestDTO productRegisterRequestDTO) {
ProductRegisterRequestDTO 일단, DB등롱이니깐 그냥 insert로 하면 될 것 같고 (ProductRequestDTO) 근데, 이것도 그냥  ProductVO로 받아서 처리하는게 나아보이는데, productNo는 0으로 처리해서... 굳이 RequestDTO가 필요할 까 함

2021-09-29 13:50 UTC, Leewongi0731 commented on src/main/java/project/springmarket/controller/ProductController.java
> +    @PostMapping("/register")
register 보다 insert를 많이 쓰고, 단순 products insert면 POST /products 면 충분할 듯.  GET/POST/DELETE자체로 의미가 있는 거니깐

2021-09-30 10:55 UTC, mankicho commented on src/main/java/project/springmarket/service/ProductService.java
> +    public ProductService(ProductRepository productRepository) {
이거뭐지.. 뭐 실수한듯

2021-09-30 10:56 UTC, mankicho commented on src/main/java/project/springmarket/controller/ProductController.java
> +    @PostMapping("/register")
ㅇㅋㅇㅋ

2021-09-30 11:41 UTC, mankicho commented on src/main/java/project/springmarket/controller/ProductController.java
> +    public boolean registerProduct(@RequestBody @Valid ProductRegisterRequestDTO productRegisterRequestDTO) {
넵 수정했습니다

2021-10-02 05:35 UTC, bbeomgeun approved these changes

2021-10-02 06:46 UTC, Leewongi0731 approved these changes

2021-10-14 14:35 UTC, merged