PR to develop from Feature/update members
study-spring/spring-market pull request #9
Opened 2021-10-11 14:09 UTC by bbeomgeun

2021-10-11 17:56 UTC, Leewongi0731 requested changes

2021-10-11 17:56 UTC, Leewongi0731 commented on src/main/java/project/springmarket/controller/MemberController.java
> +    @PatchMapping(path = "/{id}")
1. path 지워도 될 것 같고
2. mybatis param으로 객체를 넘기는 방법은 parameterType=project.springmarket.model.member.MemberAddressOnly 으로 하면 될 껄
3. Map으로 해서 하는 경우도 있는데, 그러면 실제 Map 객체를 사용하는 것이 Controller, Service가 아니라 Repository까지 내려기서 사용하는거니깐 Repository layer에서  MemberAddressOnly를 Map으로 형변환 하는게 옳아 보임

2021-10-11 17:56 UTC, Leewongi0731 commented on src/main/java/project/springmarket/model/member/MemberAddressOnly.java
> +    private int addressCodeNo;
이건 뭐임 ? pk임?

2021-10-11 17:56 UTC, Leewongi0731 commented on src/main/java/project/springmarket/controller/MemberController.java
>  @RestController
Member 관련 도메인 이니깐, /user 나 /member라는 prefix 사용하는게 좋아보임

2021-10-11 17:56 UTC, Leewongi0731 commented on src/main/java/project/springmarket/controller/MemberController.java
> +    ObjectMapper objectMapper;
이건 왜 정의한거야?

2021-10-11 17:56 UTC, Leewongi0731 commented on src/main/java/project/springmarket/controller/MemberController.java
> +    @PatchMapping(path = "/{id}")
4. 주석은 "회원 정보에서 id, pw, 주소 중에 주소 업데이트 하는 경우" 이라 선택적으로 수정하나 싶은데, request Object는 MemberAddressOnly이라 멤버의 주소와 관련된 정보만 가지고있나? 싶다가 변수 addressCodeNo, id가 튀어나오니 뭘 하고싶은지 전혀 모르겠음

2021-10-11 17:56 UTC, Leewongi0731 commented on src/main/resources/mybatis/mapper/member.xml
> +        UPDATE member set address_no = #{addressCodeNo} where id = #{id};
변수들 말고 나머지 대문자 할꺼면 set, where은 대문자로 변경해서 형식좀 지키고, 개행좀 해줘

2021-10-12 03:51 UTC, bbeomgeun commented on src/main/java/project/springmarket/controller/MemberController.java
> +    ObjectMapper objectMapper;
아 이거 이것저것 시도하다가 깜빡하고 못 지운거 같습니다 ㅎㅎ..

2021-10-13 16:06 UTC, Leewongi0731 approved these changes

2021-10-13 16:07 UTC, merged